# Generated by Django 3.2.8 on 2021-10-11 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('by', models.CharField(max_length=200)),
                ('score', models.IntegerField()),
                ('item_type', models.CharField(max_length=50)),
                ('comments', models.IntegerField()),
                ('hacker_news_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('by', models.CharField(max_length=200)),
                ('item_type', models.CharField(max_length=50)),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='published_news.publishednew', to_field='hacker_news_id')),
            ],
        ),
    ]
