# Generated by Django 3.2.8 on 2021-10-10 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('published_news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publishednews',
            old_name='descendants',
            new_name='comments',
        ),
    ]
