# Generated by Django 3.2.8 on 2021-10-10 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('published_news', '0002_rename_descendants_publishednews_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishednews',
            name='created_at',
        ),
    ]
