# Generated by Django 3.2.8 on 2021-10-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('published_news', '0003_alter_comment_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishednew',
            name='hacker_news_id',
            field=models.IntegerField(default='', unique=True),
        ),
    ]
