# Generated by Django 3.2.8 on 2021-10-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('published_news', '0004_alter_publishednew_hacker_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishednew',
            name='hacker_news_id',
            field=models.IntegerField(),
        ),
    ]
